apiVersion: apps/v1
kind: Deployment
metadata:
  name: mservice-deployment
  labels:
    app: mservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mservice
  template:
    metadata:
      labels:
        app: mservice
    spec:
      containers:
        - name: server
          image: tscolari/mservice:latest
          command: ["server"]
          env:
            - name: PORT
              value: "8080"
            - name: TAX_VALUE
              value: "0.20"
            - name: HEALTH_CHECK_PORT
              value: "9090"
          ports:
            - containerPort: 8080
              protocol: "TCP"
              name: "grpc"
            - containerPort: 9090
              protocol: "TCP"
              name: "health"
          livenessProbe:
            httpGet:
              path: /health_check
              port: 9090
            initialDelaySeconds: 5
            timeoutSeconds: 1
          readinessProbe:
            httpGet:
              path: /health_check
              port: 9090
            initialDelaySeconds: 10
            timeoutSeconds: 5

